packages:
  - apps/*
  - packages/*
overrides:
  '@esbuild-kit/core-utils>esbuild': 0.25.12
  vite: 8.0.10
allowBuilds:
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
  better-sqlite3: true
